export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const PLAN_SUCCESS = 'PLAN_SUCCESS';

export const BUDGET_PLANNER_SUCCESS = 'BUDGET_PLANNER_SUCCESS';
export const BUDGET_UPDATE_SUCCESS = 'BUDGET_UPDATE_SUCCESS';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';
export const REMOVE_EXPENSE_SUCCESS = 'REMOVE_EXPENSE_SUCCESS';