export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const CHIRP_SUCCESS = 'CHIRP_SUCCESS';
export const CREATE_CHIRP_SUCCESS = 'CREATE_CHIRP_SUCCESS';
export const REMOVE_CHIRP_SUCCESS = 'REMOVE_CHIRP_SUCCESS';

export const DISCOVER_SUCCESS = 'DISCOVER_SUCCESS';
export const FOLLOW_SUCCESS = 'FOLLOW_SUCCESS';
export const UNFOLLOW_SUCCESS = 'UNFOLLOW_SUCCESS';