export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const HOTEL_SUCCESS = 'HOTEL_SUCCESS';
export const HOTEL_DETAILS_SUCCESS = 'HOTEL_DETAILS_SUCCESS';

export const REVIEW_SUCCESS = 'HOTEL_DETAILS_SUCCESS';
export const CREATED_REVIEW_SUCCESS = 'CREATED_REVIEW_SUCCESS';