export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const STATS_SUCCESS = 'STATS_SUCCESS';

export const FETCH_FURNITURE_SUCCESS = 'FETCH_FURNITURE_SUCCESS';
export const CREATE_FURNITURE = 'CREATE_FURNITURE';
export const REMOVE_FURNITURE = 'REMOVE_FURNITURE';
export const DETAILS_FURNITURE = 'REMOVE_FURNITURE';
export const LIKE_FURNITURE = 'LIKE_FURNITURE';

export const CREATE_REVIEW = 'CREATE_REVIEW';