export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const TRIPS_SUCCESS = 'TRIPS_SUCCESS';

export const CART_GET_SUCCESS = 'CART_GET_SUCCESS';
export const REMOVE_ITEM_CART = 'REMOVE_ITEM_CART';